### ISSUE TITLE
Copied code

### ISSUE THREAD

**Issue by sujaysathya** [Anabakhtar/Proxinator#1]
You have copied most my code, I have zero problems with that. please give some sort of credit my maybe linking my bunk_bot in the Readme

**Comment by Anabakhtar** [comment]
Hey,
um, I'm really sorry that you thought I copied your code but I never even came across your bunk bot when I made my Proxinator, Infact the day I published it my friend told me about it and I was like oh others have thought about this too. Plus most importantly, Proxinator is such a simple voice recognition and basic automation script why would i even copy it? I understand your point of view henge I'm not offended by your direct allegation because it is really irritating when someone copies code and doesn't credit the author, but that's not the case here in this scenario, in fact i spent a lot of time simplifying and commenting my Proxinator code so that anyone who reads it understands it easily.
So I hope this answers your query, and also I'd suggest next time it would be really professional and polite of you to start a conversation with a discussion rather than an allegation, two people can have the same idea, and as for your code, I'm sure it must be well written but as i said, I'd not even seen it until after I had released Proxinator. Glad to sort this out.
Regards, 
Syed Anab
